// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	image: {
		repository: "surrealdb/surrealdb"
		tag:        "latest"
		digest:     ""
	}
	user:     "root"
	password: "root"
}
