apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: expedition
  namespace: default
spec:
  components:
    - name: kratos
      type: kratos-service
      properties:
        hostname: kratos.expedition.local
