apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: expedition
  namespace: default
spec:
  components:
    - name: kratos
      type: kratos-service
      properties:
        hostname: identity.expedition.local.com
    - name: surreal
      type: webservice
      properties:
        image: surrealdb/surrealdb:latest
        args:
          [
            "start",
            "--log",
            "trace",
            "--user",
            "root",
            "--pass",
            "root",
            "memory",
          ]
        ports:
          - port: 8000
            expose: true
    - name: expedition-server
      type: webservice
      properties:
        image: expedition-server:latest
        imagePullPolicy: Never
        ports:
          - port: 3000
            expose: true
        env:
          - name: EXPEDITION_SURREAL_URI
            value: surreal:8000
          - name: EXPEDITION_SURREAL_USER
            valueFrom:
              secretKeyRef:
                name: expedition-server-secrets
                key: surreal-user
          - name: EXPEDITION_SURREAL_PASS
            valueFrom:
              secretKeyRef:
                name: expedition-server-secrets
                key: surreal-password
          - name: EXPEDITION_GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: expedition-server-secrets
                key: google-api-key
      traits:
        - type: gateway
          properties:
            domain: backend.expedition.local.com
            http:
              "/": 3000
    - name: expedition-web
      type: webservice
      properties:
        image: expedition-web:latest
        imagePullPolicy: Never
      traits:
        - type: gateway
          properties:
            domain: expedition.local.com
            http:
              "/": 3000
