apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: expedition
  namespace: default
spec:
  components:
    - name: kratos
      type: kratos-service@v15
      properties:
        hostname:
          public: kratos.expedition.local
          admin: admin.kratos.expedition.local
      traits:
        - type: storage
          properties:
            configMap:
              - name: expedition-kratos-config
                mountOnly: true
                mountPath: "/etc/config"
                readOnly: true
            secret:
              - name: expedition-kratos-google
                mountOnly: true
                mountToEnvs:
                  - envName: METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
                    secretKey: client-id
                  - envName: METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
                    secretKey: client-secret
