// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	hostname: "expedition.local.com"
	image: {
		repository: "expedition-web"
		digest:     ""
		tag:        "latest"
	}

	mapboxAccessToken: ""
	googleApiKey:      ""
	origins: {
		backend: "http://backend.expedition.local.com"
		kratos:  "http://identity.expedition.local.com"
	}
}
